# What are Tensors?

### Tensors

Tensors are a specialized data structure that are very similar to arrays and matrices. 
In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.

# Initializing a Tensor

In [3]:
import numpy as np
import torch

## Directly form data

In [4]:
data = [
    [1, 2], [3, 4], [5, 6]
]

data_tensor = torch.tensor(data)
data_tensor

tensor([[1, 2],
        [3, 4],
        [5, 6]])

## From a Numpy array

In [5]:
arr = np.array(data)
arr_tensor = torch.from_numpy(arr)

print(f'Numpy arr value: \n {arr} \n')
print(f'Tensor arr_tensor value: \n {arr_tensor}')

Numpy arr value: 
 [[1 2]
 [3 4]
 [5 6]] 

Tensor arr_tensor value: 
 tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [6]:
np.multiply(arr, 2, out=arr)

print(f'Numpy arr after * 2 operation: \n {arr} \n')
print(f'Tensor arr_tensor value after modifying numpy array: \n {arr_tensor}')

Numpy arr after * 2 operation: 
 [[ 2  4]
 [ 6  8]
 [10 12]] 

Tensor arr_tensor value after modifying numpy array: 
 tensor([[ 2,  4],
        [ 6,  8],
        [10, 12]])


## From another tensor

In [7]:
x_ones = torch.ones_like(data_tensor)
x_ones

tensor([[1, 1],
        [1, 1],
        [1, 1]])

In [8]:
x_rand = torch.rand_like(data_tensor, dtype=torch.float)
x_rand

tensor([[0.1264, 0.5286],
        [0.7915, 0.4756],
        [0.4799, 0.8634]])

## With random or constant values

In [9]:
shape = (2, 3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.8874, 0.7013, 0.5191],
        [0.1543, 0.1805, 0.9077]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



# 2. Attributes of a Tensor

In [10]:
tensor = torch.rand(3, 4)

print(f"shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# 3. Operations on Tensor

In [11]:
# We move our tensor to the GPU of available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

tensor.device  

device(type='cuda', index=0)

## Indexing and Slicing

In [12]:
data = [
    [1, 2, 3], [4, 5, 6], [7, 8, 9]
]
tensor = torch.tensor(data, dtype=torch.float)

print(tensor)
print('-'*50)

print('First row:', tensor[0])
print('Last row:', tensor[-1])
print('First column:', tensor[:, 0])
print('Last column1:', tensor[:, -1])
print('Last column2:', tensor[..., -1])

print('-'*50)
tensor[:,1] = 0
tensor[1] = 0
print(tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
--------------------------------------------------
First row: tensor([1., 2., 3.])
Last row: tensor([7., 8., 9.])
First column: tensor([1., 4., 7.])
Last column1: tensor([3., 6., 9.])
Last column2: tensor([3., 6., 9.])
--------------------------------------------------
tensor([[1., 0., 3.],
        [0., 0., 0.],
        [7., 0., 9.]])


# Joining tensors

In [13]:
t0 = torch.cat([tensor, tensor], dim=0)
t0

tensor([[1., 0., 3.],
        [0., 0., 0.],
        [7., 0., 9.],
        [1., 0., 3.],
        [0., 0., 0.],
        [7., 0., 9.]])

In [14]:
t1 = torch.cat([tensor, tensor], dim=1)
t1

tensor([[1., 0., 3., 1., 0., 3.],
        [0., 0., 0., 0., 0., 0.],
        [7., 0., 9., 7., 0., 9.]])

# Arithmetic Operations

### torch.mm


performs a matrix multiplication(matrix 곱셈) 

without broadcasting - (2D tensor) by (2D tensor)




In [15]:
mat1 = torch.randn(2, 3)
mat2 = torch.randn(3, 3)

In [16]:
mat1

tensor([[-1.2521,  1.2442,  1.3088],
        [ 0.4482, -0.2707, -0.0859]])

In [17]:
mat2

tensor([[-1.9429,  0.0416, -0.0904],
        [-1.5943,  0.6634, -1.1736],
        [-1.0880, -0.0125, -1.6781]])

In [18]:
torch.mm(mat1, mat2)

tensor([[-0.9751,  0.7569, -3.5432],
        [-0.3458, -0.1599,  0.4212]])

In [19]:
torch.mm(mat2, mat1) # broadcasting이 아니기 때문에 오류 발생
# broadcasting = 부족한 수가 있을 시에 스스로 만들어줌

RuntimeError: ignored

### torch.mul

performs a elementwise multiplication(elementwise 곱셈)

with broadcasting (Tensor) by (Tensor or Number)

In [20]:
a = torch.randn(3)
a

tensor([ 1.0700, -1.7178, -1.1056])

In [21]:
torch.mul(a, 100)

tensor([ 106.9952, -171.7834, -110.5619])

In [22]:
b = torch.randn(4, 1)
b

tensor([[-0.2992],
        [ 0.5054],
        [-1.2141],
        [-0.8974]])

In [23]:
c = torch.randn(1, 4)
c

tensor([[-0.1566, -0.6396, -1.8243, -1.1417]])

In [24]:
torch.mul(b, c)

tensor([[ 0.0469,  0.1914,  0.5458,  0.3416],
        [-0.0791, -0.3233, -0.9220, -0.5770],
        [ 0.1901,  0.7765,  2.2149,  1.3861],
        [ 0.1405,  0.5740,  1.6372,  1.0246]])

### torch.matmul

matrix product with broadcasting - (tensor) by (Tensor) with different behavoirs depending on the tensor shapes

(tensor의 shape에 의존한다)

In [25]:
# vector x vector
tensor1 = torch.randn(3)
tensor2 = torch.randn(3)
torch.matmul(tensor1, tensor2).size()

torch.Size([])

In [26]:
torch.matmul(tensor1, tensor2) #matrix x vector : vector만 남는다다

tensor(-1.3384)

In [27]:
#matrix x vector
tensor1 = torch.randn(3, 4)
tensor2 = torch.randn(4)
torch.matmul(tensor1, tensor2).size()

torch.Size([3])

In [28]:
torch.matmul(tensor1, tensor2)

tensor([-0.6363,  0.7838,  1.6246])

In [29]:
#batched matrix x broadcasted vector
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(4)
torch.matmul(tensor1, tensor2).size()

torch.Size([10, 3])

In [30]:
torch.matmul(tensor1, tensor2)

tensor([[-0.6124,  2.0537, -1.0898],
        [-1.0643,  2.6769, -1.3224],
        [-2.4695,  2.6336, -5.1138],
        [-0.7803,  1.5133, -0.6430],
        [-1.5057,  3.1231,  3.0384],
        [ 5.4111,  1.4285, -0.7698],
        [ 0.2642, -6.3424, -2.2936],
        [-4.7222,  0.6910,  3.7032],
        [ 4.1738, -1.7432, -1.7866],
        [-8.4280,  3.6916,  0.3133]])

In [31]:
# batched matrix x batched matrix
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(10, 4, 5)
torch.matmul(tensor1, tensor2).size()

torch.Size([10, 3, 5])

In [32]:
#batched matrix x broadcastedd matrix
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(4, 5) # (5, 4) -> (4, 5)
torch.matmul(tensor1, tensor2).size()

torch.Size([10, 3, 5])

# Single-element tensors

In [33]:
tensor2

tensor([[-0.3026,  0.9373, -0.1503, -1.9140, -0.2300],
        [ 0.9112,  0.4274, -0.3467,  2.6014,  0.7575],
        [-1.4763, -0.0609,  0.6446,  0.0227,  0.3088],
        [-0.6659,  1.0083, -0.1815,  0.9881,  1.5260]])

In [35]:
agg = tensor2.sum()
agg

tensor(4.8052)

In [36]:
agg_item = agg.item()
agg_item

4.80517578125

In [37]:
agg_item = agg.item()
agg_item

4.80517578125

In [38]:
agg = tensor2.sum()
agg_item = agg.item() # get a value
print(agg_item, type(agg_item))

4.80517578125 <class 'float'>


# In-place operations

In [39]:
print(tensor2, "\n")
print(f"{tensor2.add(5)}\n")
print('-'*50)
print(tensor2, "\n")
tensor2.add_(5)
print(tensor2)

tensor([[-0.3026,  0.9373, -0.1503, -1.9140, -0.2300],
        [ 0.9112,  0.4274, -0.3467,  2.6014,  0.7575],
        [-1.4763, -0.0609,  0.6446,  0.0227,  0.3088],
        [-0.6659,  1.0083, -0.1815,  0.9881,  1.5260]]) 

tensor([[4.6974, 5.9373, 4.8497, 3.0860, 4.7700],
        [5.9112, 5.4274, 4.6533, 7.6014, 5.7575],
        [3.5237, 4.9391, 5.6446, 5.0227, 5.3088],
        [4.3341, 6.0083, 4.8185, 5.9881, 6.5260]])

--------------------------------------------------
tensor([[-0.3026,  0.9373, -0.1503, -1.9140, -0.2300],
        [ 0.9112,  0.4274, -0.3467,  2.6014,  0.7575],
        [-1.4763, -0.0609,  0.6446,  0.0227,  0.3088],
        [-0.6659,  1.0083, -0.1815,  0.9881,  1.5260]]) 

tensor([[4.6974, 5.9373, 4.8497, 3.0860, 4.7700],
        [5.9112, 5.4274, 4.6533, 7.6014, 5.7575],
        [3.5237, 4.9391, 5.6446, 5.0227, 5.3088],
        [4.3341, 6.0083, 4.8185, 5.9881, 6.5260]])


# Bridge with Numpy

## Tensor to Numpy array

In [40]:
t = torch.ones(5)
print(f"t : {t}")
n = t.numpy()
print(f"n: {n}")

t : tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [41]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}") # ???!!!!!

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


# Numpy array to Tensor

In [42]:
n = np.ones(5)
t = torch.from_numpy(n)

In [43]:
n

array([1., 1., 1., 1., 1.])

In [44]:
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

Changes in the Numpy array reflects in the tensor.

In [45]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"b: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
b: [2. 2. 2. 2. 2.]
